### ISSUE TITLE
[Bug] ValidationError when settting feEnvVars

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#55]
@shileifu  @kevincai
Can you take a look of this issue?
Thank you!

When setting `starrocksFESpec.feEnvVars` in the values.yaml got this error.
e.g.
![image](https://user-images.githubusercontent.com/5108773/222833360-3b103463-82b9-44be-8f75-02940787a246.png)

```
helm install starrocks . -n celostar --create-namespace \
  -f values-eu-dev-1-cs.yaml --render-subchart-notes
Error: INSTALLATION FAILED: 
unable to build kubernetes objects from release manifest: error validating "": 
error validating data: 
ValidationError(StarRocksCluster.spec.starRocksFeSpec): 
unknown field "feEnvVars" in com.starrocks.v1alpha1.StarRocksCluster.spec.starRocksFeSpec

```

**Comment by kevincai** [comment]
There is a misspelling of `feEnvVars` to `FeEnvVars`, will fix it ASAP.

**Comment by kevincai** [comment]
The `starrockscluster` crd definition fix is included in operator `v1.3` release. But it is not updated in helmchart, please manual update the crd defintion by running 
```
kubectl apply -f https://raw.githubusercontent.com/StarRocks/starrocks-kubernetes-operator/main/deploy/starrocks.com_starrocksclusters.yaml
```
Will fix the issue in helm chart.

**Comment by shileifu** [comment]
have fixed in helm chart 1.3.4

**Comment by shileifu** [comment]
I used helm kube-starrocks-1.3.4 is ok . please  share me more information about your issue, as version ...etc.

**Comment by dengliu** [comment]
It is still `feEnvVars` in the chart version 1.3.5 

![image](https://user-images.githubusercontent.com/5108773/222923567-966db4b4-5a14-45d5-9e57-e7e6da2d94aa.png)

Therefore it still fails as below if we use `feEnvVars`

```
$ helm install starrocks . -n celostar --create-namespace -f values-eu-dev-1-cs.yaml --render-subchart-notes
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StarRocksCluster.spec.starRocksFeSpec): unknown field "feEnvVars" in com.starrocks.v1alpha1.StarRocksCluster.spec.starRocksFeSpec
```

I also tried `FeEnvVars` but it doesn't take effect
```
    FeEnvVars:
      - name: AWS_REGION
        value: eu-central-1
```

**Comment by dengliu** [comment]
I also verified that `beEnvVars` has been fixed in Char V1.3.5. Thanks!
```
    beEnvVars:
      - name: AWS_REGION
        value: eu-central-1
```

**Comment by kevincai** [comment]
can you run following command to check if the crd is updated?

```
kubectl get crd starrocksclusters.starrocks.com -oyaml | grep -C 5 FeEnvVars
```
expect no output if the crd is updated correctly.

**Comment by kevincai** [comment]
reading from helm doc https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

>  There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.

It says that helm will skip upgrading or deleting crd resources.

v1.3.5 fixes the `starrocksclusters.starrocks.com` crd definition, but helm will not upgrade it by default, manual applying is necessary.

@dengliu please manually run following command to upgrade the crd and try again with `feEnvVars`

```
kubectl apply -f https://raw.githubusercontent.com/StarRocks/starrocks-kubernetes-operator/main/deploy/starrocks.com_starrocksclusters.yaml
```

**Comment by dengliu** [comment]
Thanks @kevincai 
it works after upgrading CRD.

**Comment by kevincai** [comment]
thanks for the confirmation. close this issue for now.
